name = "Hugowncast"
license = "MIT"
licenselink = "https://github.com/johanvandegriff/hugowncast/blob/master/LICENSE"
description = ""
homepage = "https://github.com/johanvandegriff/hugowncast"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Jane Vandegriff"
  homepage = "https://jjv.sh"
